
PACKAGECONFIG[bram] = "${RECIPE_SYSROOT}/usr/lib/libbram.a,,bram,,"
PACKAGECONFIG[common] = "${RECIPE_SYSROOT}/usr/lib/libcommon.a,,common,,"
PACKAGECONFIG[gpio] = "${RECIPE_SYSROOT}/usr/lib/libgpio.a,,gpio,,"
PACKAGECONFIG[sysmon] = "${RECIPE_SYSROOT}/usr/lib/libsysmon.a,,sysmon,,"
PACKAGECONFIG[uartlite] = "${RECIPE_SYSROOT}/usr/lib/libuartlite.a,,uartlite,,"